---
- hosts: webservers
  remote_user: root
  become: yes
  vars:
    -
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
