# Roles, etc. sourced from Ansible Galaxy
- src: karmab.kcli-modules
- src: geerlingguy.docker
- src: geerlingguy.pip

# Sourced from GitHub
- src: git@github.com:mrlesmithjr/ansible-mdadm.git
  scm: git