---
- import_role:
    name: karmab.kcli-modules

- name: setup kcli apt key
  apt_key:
    id: 7E3DD443A45040FC730CE463CFC88929B8FA7CB7
    url: https://packagecloud.io/karmab/kcli/gpgkey
    state: present

- name: setup kcli apt repository
  apt_repository:
    repo: deb [trusted=yes] https://packagecloud.io/karmab/kcli/ubuntu/ cosmic main
    state: present

- name: install python3-distutils package
  apt:
    name: python3-distutils
    state: present

- name: install genisoimage package
  apt:
    name: genisoimage
    state: present

- name: install kcli package
  apt:
    name: python3-kcli
    state: present

- name: set up default libvirt pool in kcli
  command: kcli pool -p /var/lib/libvirt/images default
  args:
    creates: /etc/libvirt/storage/default.xml

