---
- name: install virtualization packages
  apt:
    state: present
    name: "{{ virt_packages }}"

- name: add default user to libvirt groups
  user:
    name: "{{ default_user }}"
    groups:
    - kvm
    - libvirt
    - libvirt-qemu
    append: yes

- name: include kcli configs
  include: kcli.yml
