---
- name: install virtualization packages
  apt:
    state: present
    name: "{{ virt_packages }}"

- name: add sam to libvirt groups
  user:
    name: sam
    groups:
    - kvm
    - libvirt
    - libvirt-qemu
    append: yes

- name: include kcli configs
  include: kcli.yml