- name: install virtualization packages
  apt:
    state: present
    name: "{{ virt_packages }}"

# TODO
# - name: setup bridge interfaces
# - name: create storage pools
# - name: create VM definitions