---
- name: Create docker unifi-controller project directory
  file:
    state: directory
    path: "{{ docker_unifi_controller_project_dir }}"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0755'

- name: Template docker-compose.yaml.j2 to project directory
  template:
    src: docker-compose.yaml.j2
    dest: "{{ docker_unifi_controller_project_dir }}/docker-compose.yml"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0644'
    validate: docker-compose -f %s config

- name: Run unifi-controller docker-compose project
  docker_compose:
    state: present
    project_name: unifi-controller
    project_src: "{{ docker_unifi_controller_project_dir }}"
  register: output

- name: Template config.gateway.json for wireguard configuration
  template:
    src: config.gateway.json.j2
    dest: "{{ config_volume_dir }}/unifi/data/sites/default/config.gateway.json"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0644'

- debug:
    var: output
    verbosity: 3
