---
- name: Create docker network services project directory
  file:
    state: directory
    path: "{{ docker_networkservices_project_dir }}"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0755'

- name: Template docker-compose.yaml.j2 to project directory
  template:
    src: docker-compose.yaml.j2
    dest: "{{ docker_networkservices_project_dir }}/docker-compose.yml"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0644'
    validate: docker-compose -f %s config

- name: Run unifi-controller docker-compose project
  docker_compose:
    state: present
    project_name: unifi-controller
    project_src: "{{ docker_networkservices_project_dir }}"
  register: output

- debug:
    var: output
    verbosity: 3
