---
- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Install common packages
  include: packages.yml

- name: Configure passwordless sudo
  include: sudo.yml

- name: Set up users
  include: users.yml

- name: Configure SSH
  include: ssh.yml