---
- name: set up default user
  user:
    name: "{{ default_user }}"
    groups:
    - sudo
    append: yes

- name: install default user SSH public keys
  authorized_key:
    key: "https://github.com/{{ default_user_github }}.keys"
    user: "{{ default_user }}"
