---
# Install docker and do initial setup
- import_role:
    name: geerlingguy.docker
  vars:
    docker_edition: 'ce'
    docker_package_state: latest
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_users:
    - sam

# Install pip, then install docker python library
- import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker

# Create raid array for media storage volume
- import_role:
    name: ansible-mdadm
  vars:
    mdadm_arrays:
      - name: "{{ mdraid_volume1_name }}"
        state: present
        level: 1
        devices:
        - /dev/sdc
        - /dev/sdd
        filesystem: ext4
        mountpoint: "{{ mdraid_volume1_mountpoint }}"
        opts: 'noatime'

- name: Mount /dev/sda to /mnt/sda
  mount:
    state: mounted
    path: /mnt/sda
    src: /dev/sda
    fstype: ext4
    opts: noatime

- name: Template docker-compose.yaml.j2 to /home/sam/docker-compose.yml
  template:
    src: docker-compose.yaml.j2
    dest: /home/sam/docker-compose.yml
    owner: sam
    group: sam
    mode: '0644'
    validate: docker-compose -f %s config
