---
- import_role:
    name: geerlingguy.docker
  vars:
    docker_edition: 'ce'
    docker_package_state: latest
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_users:
    - sam

- import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker

- import_role:
    name: ansible-mdadm
  vars:
    mdadm_arrays:
      - name: "{{ mdraid_volume1_name }}"
        state: present
        level: 1
        devices:
        - /dev/sdc
        - /dev/sdd
        filesystem: ext4
        mountpoint: "{{ mdraid_volume1_mountpoint }}"
        opts: 'noatime'

- name: pull UniFi Controller docker image
  docker_image:
    name: linuxserver/unifi-controller
    source: pull

- name: create UniFi Controller container
  docker_container:
    name: unifi-controller
    image: linuxserver/unifi-controller
    env:
      PUID: "1000"
      PGID: "1000"
      MEM_LIMIT: "1024M"
    volumes:
      - /config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart_policy: unless-stopped

- name: Template docker-compose.j2 to /home/sam/docker-compose.yml
  template:
    src: docker-compose.j2
    dest: /home/sam/docker-compose.yml
    owner: sam
    group: sam
    mode: '0644'