---
# Install docker and do initial setup
- import_role:
    name: geerlingguy.docker
  vars:
    docker_edition: 'ce'
    docker_package_state: latest
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_users:
    - sam
    docker_install_compose: false

# Install pip, then install docker python library
- import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_executable: pip3

- name: install docker-related pip packages
  pip:
    name: "{{ pip_install_docker_packages }}"
    executable: pip3
    state: latest

- name: Mount docker config volume 
  mount:
    state: mounted
    path: "{{ config_volume_mountpoint }}"
    src: "{{ config_volume_device }}"
    fstype: ext4
    opts: noatime

- name: Create directory for docker-compose projects
  file:
    state: directory
    path: /home/sam/docker
    owner: sam
    group: sam
    mode: '0755'
