---
- import_role:
    name: geerlingguy.docker
  vars:
    docker_edition: 'ce'
    docker_package_state: latest
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_users:
    - sam

- import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker

- import_role:
    name: ansible-mdadm
  vars:
    mdadm_arrays:
      - name: md0
        state: present
        level: 1
        devices:
        - /dev/sdc
        - /dev/sdd
        filesystem: ext4
        mountpoint: /mnt/md0
        opts: 'noatime'

- name: pull Plex docker image
  docker_image:
    name: linuxserver/plex
    source: pull

- name: create Plex container
  docker_container:
    name: plexserver
    image: linuxserver/plex
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
      UMASK_SET: "022"
    volumes:
      - /mnt/md0/plexconfig:/config
      - /mnt/md0/media/tv:/tv
      - /mnt/md0/media/movies:/movies
      - /transcode
    restart_policy: unless-stopped

- name: pull UniFi Controller docker image
  docker_image:
    name: linuxserver/unifi-controller
    source: pull

- name: create UniFi Controller container
  docker_container:
    name: unifi-controller
    image: linuxserver/unifi-controller
    env:
      PUID: "1000"
      PGID: "1000"
      MEM_LIMIT: "1024M"
    volumes:
      - /config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart_policy: unless-stopped