---
# Install docker and do initial setup
- import_role:
    name: geerlingguy.docker
  vars:
    docker_edition: 'ce'
    docker_package_state: latest
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_users:
    - sam

# Install pip, then install docker python library
- import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker

- name: Mount docker config volume 
  mount:
    state: mounted
    path: "{{ config_volume_mountpoint }}"
    src: "{{ config_volume_device }}"
    fstype: ext4
    opts: noatime

- name: Create directory for docker-compose projects
  file:
    state: directory
    path: /home/sam/docker
