---
- name: Create docker pi-hole project directory
  file:
    state: directory
    path: "{{ docker_pi_hole_project_dir }}"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0755'

- name: Template docker-compose.yaml.j2 to project directory
  template:
    src: docker-compose.yaml.j2
    dest: "{{ docker_pi_hole_project_dir }}/docker-compose.yml"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0644'
    validate: docker-compose -f %s config

- name: Run pi-hole docker-compose project
  docker_compose:
    state: present
    project_name: pi-hole
    project_src: "{{ docker_pi_hole_project_dir }}"
  register: output

- debug:
    var: output
    verbosity: 3
