- name: Create docker media project directory
  file:
    state: directory
    path: "{{ docker_media_project_dir }}"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0755'

- name: Template docker-compose.yaml.j2 to docker project directory
  template:
    src: docker-compose.yaml.j2
    dest: "{{ docker_media_project_dir }}/docker-compose.yml"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0644'
    validate: docker-compose -f %s config

# - name: Run media-server docker-compose project
#   docker_compose:
#     state: present
#     project_name: media-server
#     project_src: "{{ docker_media_project_dir }}"
#   register: output
#
#- debug:
#    var: output
#    verbosity: 3
