---
# # Applies necessary configs to get a Docker host up and running
# - hosts: docker_hosts
#   become: true
#   roles:
#   - common
#   - bastion
#   - docker

# Run host-specific docker roles
- hosts: gambler01
  become: true
  roles:
    - media-server
    - unifi-controller
